In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt 
from math import log,sqrt,pow
import math
import random
from matplotlib.font_manager import FontProperties

In [2]:
datanumber=2484
def unpickle(file):
    import pickle
    with open(file,'rb')as fo:
        dict =pickle.load(fo,encoding='bytes')
        
    return dict

path='D:/ML-generate/imagecluster-v3/'

data_array=np.zeros((2484,3072))

cur_dict=unpickle(path+'data_batch_'+str(1))
for j in range(2484):
    data_array[j]=cur_dict[b'data'][j][:]       

data_array=data_array.reshape(2484,3,32,32).transpose(0,2,3,1).astype('float32')

In [3]:
def pHash(img):
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    h,w=gray.shape[:2]
    vis0=np.zeros((h,w),np.float32)
    vis0[:h,:w]=gray
    
    vis1=cv2.dct(vis0)
    img_list=vis1.flatten()

    avg=sum(img_list)*1./len(img_list)
    avg_list=['0' if i <avg else '1' for i in img_list] 

    hash=''.join(['%x '% int(''.join(avg_list[x:x+4]),2)for x in range(0,32*32,4)])
    hash1=[int(x,16) for x in hash.split()]
    return hash1

In [4]:
feature=[]
for i in range(datanumber):
    img=data_array[i,:,:,:].astype('uint8')
    feature.append(pHash(img))

In [5]:
from sklearn.decomposition import PCA  
pca = PCA(n_components=3)              
newData = pca.fit_transform(feature)
print(newData)

p1=[]
p2=[]
p3=[]

for i in range(datanumber):
        p1.append(newData[i][0])
        p2.append(newData[i][1])
        p3.append(newData[i][2])
        
file=open('D:/ML-generate/imagecluster-v3/p1.txt','w')
file.write(str(p1));
file.close()
file=open('D:/ML-generate/imagecluster-v3/p2.txt','w')
file.write(str(p2));
file.close()
file=open('D:/ML-generate/imagecluster-v3/p3.txt','w')
file.write(str(p3));
file.close()


[[ 18.41164589 -12.48989569   8.80026512]
 [ -3.8954062   -6.81529293  -1.00933754]
 [  3.45423598  -7.66388448   0.29602388]
 ...
 [ 10.53653911 -12.81979774 -11.72848991]
 [  3.95233759   4.23905574  -2.57277818]
 [ 15.48806651   4.57597427   8.70465315]]
